#!/bin/bash
# SmartDormX — One-command launcher
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║           SmartDormX — Smart Hostel Management System       ║"
echo "║           PAF-IAST Final Year Project 2026                   ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  Recognition Engine: OpenCV DNN ResNet-SSD + FisherFace     ║"
echo "║  Database:           SQLite (local) + Supabase-compatible API║"
echo "║  Auth:               Demo mode — any credentials accepted    ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo ""
echo "  Starting Flask server on http://localhost:5000 ..."
echo ""
echo "  ► Admin Portal:    open frontend/sign-in.html"
echo "    (or http://localhost:5000)"
echo ""
echo "  ► Student Portal:  open student-portal/sign-in.html"
echo ""
echo "  ► REST API:        http://localhost:5000/api/<table>"
echo "    Tables: students · announcements · requests"
echo "            payments_hostel · payments_mess · mess_menu"
echo "            mess_attendance · mess_feedback · dashboard_alerts"
echo ""
echo "  ► Live Camera:     http://localhost:5000/video_feed"
echo ""
echo "  Press Ctrl+C to stop."
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
cd "$(dirname "$0")/backend"
python3 app.py
